version: '3'
services:
  web:
    image: venmaum/omed:new
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/omed
    ports:
      - "8000:8000"
